version: "3.9"
volumes:
  shared-workspace:
services:
  spark-master:
    build: 
      context: . 
      dockerfile: Dockerfile
      args:
        tipo: "master"
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    build: 
      context: . 
      dockerfile: Dockerfile
      args:
        tipo: "worker"
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
